-- This file has been generated by notion. Do not edit.
return {
    [0] = {
        ["type"] = "WRootWin",
        ["name"] = "WRootWin",
        ["managed"] = {
            [1] = {
                ["type"] = "WGroupWS",
                ["name"] = "WGroupWS",
                ["level"] = 0,
                ["switchto"] = true,
                ["sizepolicy"] = "full",
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1920,
                    ["h"] = 1200,
                },
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling",
                        ["bottom"] = true,
                        ["sizepolicy"] = "full",
                        ["level"] = 0,
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1920,
                            ["h"] = 1200,
                        },
                        ["split_tree"] = {
                            ["tls"] = 960,
                            ["tl"] = {
                                ["tls"] = 1185,
                                ["tl"] = {
                                    ["regparams"] = {
                                        ["managed"] = {
                                            [1] = {
                                                ["type"] = "WGroupCW",
                                                ["name"] = "WGroupCW",
                                                ["level"] = 0,
                                                ["switchto"] = true,
                                                ["sizepolicy"] = "full",
                                                ["geom"] = {
                                                    ["y"] = 19,
                                                    ["x"] = 1,
                                                    ["w"] = 958,
                                                    ["h"] = 1165,
                                                },
                                                ["managed"] = {
                                                    [1] = {
                                                        ["type"] = "WClientWin",
                                                        ["level"] = 1,
                                                        ["bottom"] = true,
                                                        ["checkcode"] = 1,
                                                        ["sizepolicy"] = "full",
                                                        ["geom"] = {
                                                            ["y"] = 3,
                                                            ["x"] = 2,
                                                            ["w"] = 954,
                                                            ["h"] = 1159,
                                                        },
                                                        ["windowid"] = 6291461,
                                                    },
                                                },
                                            },
                                        },
                                        ["mode"] = 1,
                                        ["name"] = "WFrame",
                                        ["type"] = "WFrame",
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                                ["dir"] = "vertical",
                                ["type"] = "WSplitSplit",
                                ["br"] = {
                                    ["type"] = "WSplitST",
                                },
                                ["brs"] = 15,
                            },
                            ["dir"] = "horizontal",
                            ["type"] = "WSplitSplit",
                            ["br"] = {
                                ["regparams"] = {
                                    ["managed"] = {
                                        [1] = {
                                            ["type"] = "WGroupCW",
                                            ["name"] = "WGroupCW<1>",
                                            ["level"] = 0,
                                            ["switchto"] = true,
                                            ["sizepolicy"] = "full",
                                            ["geom"] = {
                                                ["y"] = 19,
                                                ["x"] = 1,
                                                ["w"] = 958,
                                                ["h"] = 1180,
                                            },
                                            ["managed"] = {
                                                [1] = {
                                                    ["type"] = "WClientWin",
                                                    ["level"] = 1,
                                                    ["bottom"] = true,
                                                    ["checkcode"] = 2,
                                                    ["sizepolicy"] = "full",
                                                    ["geom"] = {
                                                        ["y"] = 2,
                                                        ["x"] = 2,
                                                        ["w"] = 954,
                                                        ["h"] = 1177,
                                                    },
                                                    ["windowid"] = 6291938,
                                                },
                                            },
                                        },
                                    },
                                    ["mode"] = 1,
                                    ["name"] = "WFrame<1>",
                                    ["type"] = "WFrame",
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["brs"] = 960,
                        },
                    },
                },
            },
            [2] = {
                ["type"] = "WGroupWS",
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["sizepolicy"] = "free_glue",
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*",
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["level"] = 1025,
                        ["geom"] = {
                            ["y"] = 360,
                            ["x"] = 640,
                            ["w"] = 640,
                            ["h"] = 480,
                        },
                        ["mode"] = 0,
                    },
                },
                ["unnumbered"] = true,
                ["name"] = "*scratchws*",
                ["hidden"] = true,
                ["pseudomodal"] = true,
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1920,
                    ["h"] = 1200,
                },
                ["level"] = 1,
            },
        },
    },
}

