-- This file has been generated by notion. Do not edit.
return {
    [1] = "menu.mainmenu:session/exit",
    [2] = "run:google-chrome",
    [3] = "run:launch_maps",
    [4] = "workspacelayout:",
    [5] = "workspacename:",
    [6] = "run:eclipse-indigo",
    [7] = "workspacename:music",
    [8] = "workspacename:test",
    [9] = "run:/home/moveek/bin/launch_maps",
    [10] = "framename:main",
    [11] = "run:terminal",
    [12] = "run:eclipse",
    [13] = "menu.mainmenu:session/restart",
    [14] = "run:firefox",
    [15] = "run:gnome-terminal",
}

