#!/usr/bin/env bash

#icon="$HOME/pics/icons/icons8-lock.svg"
tmpbg='/tmp/screen.png'

if [[ -f ${tmpbg} ]]; then
	rm ${tmpbg}	
fi

#(( $# )) && { icon=$1; }

scrot "$tmpbg"
convert "$tmpbg" -scale 10% -scale 1000% "$tmpbg"
#convert "$tmpbg" "$icon" -gravity center -composite -matte "$tmpbg"
i3lock -i "$tmpbg"
