#!/bin/bash

print_to_file() {
   PROP="${1}"
   VAL="${2}"
   printf "${PROP} = ${VAL}\n" >> ${CONF_FILE} 
}

# Make tiddlywiki config directory if it doesn't exist
CONF_DIR=${HOME}/.config/tiddlywiki
CONF_FILE=${CONF_DIR}/tiddlywiki.info

if [[ -a ${CONF_FILE} && ! $1 = "-u" ]]; then
    printf "Skip generate info file. File exists. Pass -u to update info.\n\n";
    cat ${CONF_FILE}
    exit 0;
fi

mkdir -p ${CONF_DIR}

## Populate base properties ##

# node_modules location
NODE_MODULES_HOME_PROP="node_modules_home"
NPM_PATH=`npm | tail -1 | awk '{print $2}'`
NODE_MODULES_HOME=`dirname ${NPM_PATH}`


# tiddlywiki npm package install location
TW_NODE_MODULE_INSTALL_LOCATION_PROP="tw_node_module_location"
TW_NODE_MODULE_INSTALL_LOCATION=

if [[ -d ${NODE_MODULES_HOME}/tiddlywiki ]];then
    TW_NODE_MODULE_INSTALL_LOCATION="${NODE_MODULES_HOME}/tiddlywiki"
fi


# Check if the tiddlywiki npm package is installed and whether it's installed as a symlink
# to an external path, such as a checkout of the git repo.
TW_INSTALL_TYPE_PROP="tw_installation_type"
TW_EXTERNAL_LOCATION_PROP="tw_external_location"
TW_VERSION_PROP="tw_version"

TW_PKG_INFO=`npm ls -g tiddlywiki | sed '/^$/d' | tail -1`
TW_INSTALL_TYPE=
TW_EXTERNAL_LOCATION=
TW_VERSION=

# If tiddlywiki is not installed then the output of "npm ls" will contain the string "empty".
if ! [[ $TW_PKG_INFO =~ "empty" ]];then
    TW_VERSION=`echo $TW_PKG_INFO | awk '{print $2}'`

fi

# determine if tiddlywiki was installed via:
# 1) npm package directly via npm install
# 2) link to checked out git directory
# 3) link to plain extracted src directory (from src zip)."
if [[ $TW_PKG_INFO =~ "->" ]];then
   TW_INSTALL_TYPE="external"
   TW_EXTERNAL_LOCATION=`echo $TW_PKG_INFO | awk '{print $4}'` 
else
   TW_INSTALL_TYPE="installed npm package"
fi

if [[ -d ${TW_EXTERNAL_LOCATION}/.git ]];then
   TW_INSTALL_TYPE="${TW_INSTALL_TYPE} git repo"
else
   TW_INSTALL_TYPE="${TW_INSTALL_TYPE} src repo"
fi

## Path and symlink summary

BIN_LOCATION=`which tiddlywiki`
BIN_SYMLINK_DETAIL=`ls -l ${BIN_LOCATION}`
BIN_SYMLINK_DETAIL="/${BIN_SYMLINK_DETAIL#*/}" # Strip off the permission, owner, date file info

TW_NODE_SYMLINK_DETAIL=`ls -l ${NODE_MODULES_HOME}/tiddlywiki`
TW_NODE_SYMLINK_DETAIL="/${TW_NODE_SYMLINK_DETAIL#*/}"

printf "\n"
printf "Summary: \n\n" >> ${CONF_FILE}
printf "${BIN_SYMLINK_DETAIL}\n" >> ${CONF_FILE}
printf "${TW_NODE_SYMLINK_DETAIL}\n\n" >> ${CONF_FILE}

printf "Detail: \n\n"
print_to_file "${NODE_MODULES_HOME_PROP}" "${NODE_MODULES_HOME}"
print_to_file "${TW_NODE_MODULE_INSTALL_LOCATION_PROP}" "${TW_NODE_MODULE_INSTALL_LOCATION}"
print_to_file "${TW_INSTALL_TYPE_PROP}" "${TW_INSTALL_TYPE}"
print_to_file "${TW_EXTERNAL_LOCATION_PROP}" "${TW_EXTERNAL_LOCATION}"
print_to_file "${TW_VERSION_PROP}" "${TW_VERSION}"

cat ${CONF_FILE}
